# Generated by Django 4.1.7 on 2023-04-08 12:18

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('period', models.CharField(max_length=11, null=True)),
            ],
            options={
                'verbose_name_plural': 'Education companies',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='backend.educationcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('background', models.FileField(upload_to='')),
                ('tools', models.ManyToManyField(to='backend.tool')),
            ],
        ),
        migrations.AddField(
            model_name='educationcompany',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.lang'),
        ),
    ]
