# Generated by Django 4.1.7 on 2023-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tool',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
