# Generated by Django 4.1.7 on 2023-04-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.lang')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
