# Generated by Django 4.1.7 on 2023-03-20 18:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_project_background_alter_tool_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='img',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
