# Generated by Django 4.1.7 on 2023-03-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_educationorganization_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationOrganization',
            new_name='EducationCompany',
        ),
    ]
