# Generated by Django 4.1.7 on 2023-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='dmitry.votchitsev@gmail.com', max_length=254),
        ),
    ]
