# Generated by Django 4.1.7 on 2023-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about_me',
            field=models.TextField(default='Text about me...', max_length=600),
        ),
    ]
