# Generated by Django 4.1.7 on 2023-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_lang_educationcompany_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationcompany',
            name='period',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
