# Generated by Django 4.1.7 on 2023-03-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_skill_organization_skill_company_skill_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='backend.educationcompany'),
        ),
    ]
