# Generated by Django 4.1.7 on 2023-03-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_skill_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='lang',
        ),
    ]
