# Generated by Django 4.1.7 on 2023-04-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_skill_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationcompany',
            options={'verbose_name_plural': 'Education companies'},
        ),
        migrations.AlterModelOptions(
            name='lang',
            options={'verbose_name_plural': 'Languages'},
        ),
    ]
