# Generated by Django 4.1.7 on 2023-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
