# Generated by Django 4.1.7 on 2023-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_bot', '0002_alter_message_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
